spring.application.name=inventario-activos

server.port=8081

server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=INVENTARIO_USER
spring.datasource.password=inventario_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

# Muestra la traza detallada de excepciones en controladores web
logging.level.org.springframework.web=DEBUG

# Muestra los logs específicos de tu paquete principal (ajusta com.example.inventario_activos)
logging.level.com.example.inventario_activos=DEBUG

# Muestra excepciones detalladas en la respuesta si estás en entorno local
server.error.include-stacktrace=always
server.error.include-message=always